/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package odev.ui;

import javax.swing.JFrame;

/**
 *
 * @author Asus
 */
public class UygulamaEkrani extends javax.swing.JFrame {

            /**
             * Creates new form UygulamaEkrani
             */
            
            
            public UygulamaEkrani() {
                        initComponents();
                        setSize(1200,700);
                        setResizable(false);
                        
                   
                        
                        
                        
            }
            
            /**
             * This method is called from within the constructor to initialize
             * the form. WARNING: Do NOT modify this code. The content of this
             * method is always regenerated by the Form Editor.
             */
            @SuppressWarnings("unchecked")
            // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
            private void initComponents() {

                        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                        setTitle("Taş Kağıt Makas");
                        setPreferredSize(new java.awt.Dimension(1200, 700));
                        setSize(new java.awt.Dimension(1200, 700));

                        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                        getContentPane().setLayout(layout);
                        layout.setHorizontalGroup(
                                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGap(0, 800, Short.MAX_VALUE)
                        );
                        layout.setVerticalGroup(
                                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGap(0, 400, Short.MAX_VALUE)
                        );

                        pack();
            }// </editor-fold>//GEN-END:initComponents
            

            public static void main(String args[]) {
                       uygulama = new UygulamaEkrani(); 
                        uygulama.setVisible(true); 
                        uygulama.girisSayfasiniAc();
                        
                        
            }
            /**
            Oyuncu isimleri ve tur sayısını aldığımız sayfayı başlatır
            **/
            public void girisSayfasiniAc() {  
                        setContentPane(new GirisEkrani());
                        repaint();
                        setVisible(true);
                        
            }
            
            /**
             * 
             * @param oyuncuismi1
             * @param oyuncuismi2
             * @param tursayisi 
             * taş kağıt makas oyun sürecini başlatır
             */
            public void oyunSayfasiniAc(String oyuncuismi1,String oyuncuismi2,Object tursayisi){
                        System.out.println("Birinci oyuncu ismi :"+oyuncuismi1+" " +"İkinci Oyuncu İsmi"+oyuncuismi2+" "+"Tur Sayisi"+tursayisi);
                        setContentPane(new OyunEkrani(oyuncuismi1,oyuncuismi2,tursayisi));
                        repaint();
                        setVisible(true);
           
            }
            
            /**
             * 
             * @param ilkoyuncuskor
             * @param ikincioyuncuskor
             * @param oyuncuismi1
             * @param oyuncuismi2 
             * 
             * oyuncu ismini yazdırır
             */
            public void sonucSayfasiniAc(int ilkoyuncuskor,int ikincioyuncuskor,String oyuncuismi1,String oyuncuismi2){
                        setContentPane(new SonucEkrani(ilkoyuncuskor,ikincioyuncuskor,oyuncuismi1,oyuncuismi2));
                        repaint();
                        setVisible(true);
           
            }            
            
            public static UygulamaEkrani uygulama;
            private odev.ui.GirisEkrani girisEkrani;
            // Variables declaration - do not modify//GEN-BEGIN:variables
            // End of variables declaration//GEN-END:variables
}
